In [53]:
from fastai.text.all import *

import pdb

In [1]:
# !wget https://s3.amazonaws.com/text-datasets/nietzsche.txt

--2023-03-29 11:36:46--  https://s3.amazonaws.com/text-datasets/nietzsche.txt
Resolving s3.amazonaws.com (s3.amazonaws.com)... 52.217.77.102, 52.216.62.152, 52.217.107.94, ...
Connecting to s3.amazonaws.com (s3.amazonaws.com)|52.217.77.102|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 600901 (587K) [text/plain]
Saving to: ‘nietzsche.txt’

nietzsche.txt       100%[===================>] 586,82K  1,22MB/s    in 0,5s    

2023-03-29 11:36:47 (1,22 MB/s) - ‘nietzsche.txt’ saved [600901/600901]



In [3]:
text = open('nietzsche.txt').read()

In [4]:
chars = sorted(list(set(text)))
vocab_size = len(chars)+1
print('total chars:', vocab_size)

total chars: 85


In [5]:
chars.insert(0, "\0")

''.join(chars)

'\x00\n !"\'(),-.0123456789:;=?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_abcdefghijklmnopqrstuvwxyzÆäæéë'

In [6]:
char_indices = {c: i for i, c in enumerate(chars)}
indices_char = {i: c for i, c in enumerate(chars)}

In [7]:
tokens = L([c for c in text])
tokens

(#600893) ['P','R','E','F','A','C','E','\n','\n','\n'...]

In [8]:
nums = L(char_indices[i] for i in tokens)
nums

(#600893) [40,42,29,30,25,27,29,1,1,1...]

In [9]:
sl = 3

L([
    (tokens[i:i+sl], tokens[i+sl]) for i in range(len(tokens)-sl)
])

(#600890) [(['P', 'R', 'E'], 'F'),(['R', 'E', 'F'], 'A'),(['E', 'F', 'A'], 'C'),(['F', 'A', 'C'], 'E'),(['A', 'C', 'E'], '\n'),(['C', 'E', '\n'], '\n'),(['E', '\n', '\n'], '\n'),(['\n', '\n', '\n'], 'S'),(['\n', '\n', 'S'], 'U'),(['\n', 'S', 'U'], 'P')...]

In [10]:
L([
    (tensor(nums[i:i+sl]), nums[i+sl]) for i in range(len(tokens)-sl)
])

(#600890) [(tensor([40, 42, 29]), 30),(tensor([42, 29, 30]), 25),(tensor([29, 30, 25]), 27),(tensor([30, 25, 27]), 29),(tensor([25, 27, 29]), 1),(tensor([27, 29,  1]), 1),(tensor([29,  1,  1]), 1),(tensor([1, 1, 1]), 43),(tensor([ 1,  1, 43]), 45),(tensor([ 1, 43, 45]), 40)...]

In [11]:
d = nums[:100000]


data = L([
    (tensor(d[i:i+sl]), d[i+sl]) for i in range(len(d)-sl)
])

In [12]:
bs = 1024
cut = int(len(data) * 0.8)
dls = DataLoaders.from_dsets(data[:cut], data[cut:], bs=bs, shuffle=False)

In [13]:
xb, yb = dls.one_batch()
xb.shape

torch.Size([1024, 3])

In [14]:
yb

tensor([30, 25, 27,  ..., 56, 58, 72])

In [15]:
class Char3Model(nn.Module):
    def __init__(self, vocab_size, n_hidden):
        super().__init__()
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.h_h = nn.Linear(n_hidden, n_hidden) # [256,256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, x):
        # x = [1024, 3]
        
        in1 = self.i_h(x[:,0]) # [1024, 256]
        h1 = F.tanh(self.h_h(in1)) # [1024, 256]
        
        in2 = self.i_h(x[:,1]) # [1024, 256]
        h2 =  F.tanh(self.h_h(h1 + in2)) # [1024, 256]
        
        in3 = self.i_h(x[:,2]) # [1024, 256]
        h3 = F.tanh(self.h_h(h2 + in3)) # [1024, 256]
        
        out = self.h_o(h3) #[1024, 85]
        
        return out
    

In [17]:
model = Char3Model(vocab_size, 256)

learner = Learner(dls, model, loss_func=F.cross_entropy)

In [18]:
learner.fit_one_cycle(10, 1e-2)

/Users/lucasvanwalstijn/mambaforge/lib/python3.10/site-packages/torch/nn/functional.py:1956: UserWarning: nn.functional.tanh is deprecated. Use torch.tanh instead.
  warnings.warn("nn.functional.tanh is deprecated. Use torch.tanh instead.")


In [19]:
class CharXModel(nn.Module):
    def __init__(self, vocab_size, n_hidden):
        super().__init__()
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.h_h = nn.Linear(n_hidden, n_hidden) # [256,256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # x = [1024, "sl"]
        
        h = 0.
        for i in range(xs.shape[1]):
            h = h + self.i_h(xs[:,i]) # [1024, 256]
            h = F.tanh(self.h_h(h)) # [1024, 256]
                
        out = self.h_o(h) #[1024, 85]
        
        return out
        

In [20]:
model = CharXModel(vocab_size, 256)
learner = Learner(dls, model, loss_func=F.cross_entropy)
learner.fit_one_cycle(10, 1e-2)

In [24]:
class CharXConcatModel(nn.Module):
    def __init__(self, vocab_size, n_hidden):
        super().__init__()
        self.vocab_size = vocab_size
        self.n_hidden = n_hidden
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.h_h = nn.Linear(n_hidden+n_hidden, n_hidden) # [256x2,256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # x = [1024, "sl"]
        
        bs = xs.shape[0]
        h = torch.zeros(bs,self.n_hidden)
        for i in range(xs.shape[1]):
            h = torch.cat([h, self.i_h(xs[:,i])], dim=1) # [1024, 512]
            h = F.tanh(self.h_h(h)) # [1024, 256]
                
        out = self.h_o(h) #[1024, 85]
        
        return out
        

In [25]:
model = CharXConcatModel(vocab_size, 256)
learner = Learner(dls, model, loss_func=F.cross_entropy)
learner.fit_one_cycle(10, 1e-2)

In [26]:
class CharXRNNModel(nn.Module):
    def __init__(self, vocab_size, n_hidden):
        super().__init__()
        self.vocab_size = vocab_size
        self.n_hidden = n_hidden
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.rnn = nn.RNN(256, 256) # [256, 256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, sl]
        
        bs = xs.shape[0] # 1024
        h = torch.zeros(1, bs, self.n_hidden) # [1,1024, 256]
        
        x = self.i_h(xs) # [1024, sl, 256]
        
        hs, h = self.rnn(x.transpose(0,1), h)
        # hs [sl, 1024, 256]
        # h [1, 1024, 256]
        
        out = self.h_o(h.squeeze())
        
        return out
        

In [27]:
model = CharXRNNModel(vocab_size, 256)
learner = Learner(dls, model, loss_func=F.cross_entropy)
learner.fit_one_cycle(10, 1e-2)

In [28]:
class CustomRNN(nn.Module):
    def __init__(self, n_in, n_out):
        super().__init__()
        self.n_in = n_in
        self.n_out = n_out
        
        self.l_hidden = nn.Linear(n_in, n_out)
        
    def forward(self, xs, h):
        # xs [sl, 1024, 256]
        # h  [1024, 256]
        hs = []
        for x in xs:
            inp = x + h # [1024, 256]
            h = torch.tanh(self.l_hidden(inp))
            hs.append(h)
        return torch.stack(hs), h


class CharXCustomRNNModel(nn.Module):
    def __init__(self, vocab_size, n_hidden):
        super().__init__()
        self.vocab_size = vocab_size
        self.n_hidden = n_hidden
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.rnn = CustomRNN(256, 256)
        # self.h_h = nn.Linear(n_hidden, n_hidden) # [256,256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, sl]
        
        bs = xs.shape[0] # 1024
        
        h = torch.zeros(bs, self.n_hidden) # [1024, 256]
        x = self.i_h(xs) # [1024, sl, 256]
        
        hs, h = self.rnn(x.transpose(0,1), h)
        # hs [sl, 1024, 256]
        # h [1024, 256]
        
        out = self.h_o(h)
        
        return out
        

In [29]:
model = CharXCustomRNNModel(vocab_size, 256)
learner = Learner(dls, model, loss_func=F.cross_entropy)
learner.fit_one_cycle(10, 1e-2)

In [30]:
class CustomConcatRNN(nn.Module):
    def __init__(self, n_in, n_out):
        super().__init__()
        self.n_in = n_in
        self.n_out = n_out
        
        self.l_hidden = nn.Linear(2*n_in, n_out)
        
    def forward(self, xs, h):
        # xs [sl, 1024, 256]
        # h  [1024, 256]
        hs = []
        for x in xs:
            inp = torch.cat([x, h], dim=1) # [1024, 512]
            h = torch.tanh(self.l_hidden(inp))
            hs.append(h)
        return torch.stack(hs), h


class CharXCustomConcatRNNModel(nn.Module):
    def __init__(self, vocab_size, n_hidden):
        super().__init__()
        self.vocab_size = vocab_size
        self.n_hidden = n_hidden
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.rnn = CustomConcatRNN(256, 256)
        # self.h_h = nn.Linear(n_hidden, n_hidden) # [256,256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, sl]
        
        bs = xs.shape[0] # 1024
        
        h = torch.zeros(bs, self.n_hidden) # [1024, 256]
        x = self.i_h(xs) # [1024, sl, 256]
        
        hs, h = self.rnn(x.transpose(0,1), h)
        # hs [sl, 1024, 256]
        # h [1024, 256]
        
        out = self.h_o(h)
        
        return out
        

In [31]:
model = CharXCustomConcatRNNModel(vocab_size, 256)
learner = Learner(dls, model, loss_func=F.cross_entropy)
learner.fit_one_cycle(10, 1e-2)

### Now let's make this more efficient by using a different way to load the data

In [32]:
data = [
    (tensor(d[i:i+sl]), tensor(d[i+1:i+1+sl])) for i in range(0, len(d)-sl, sl)
]

In [33]:
data[0]

(tensor([40, 42, 29]), tensor([42, 29, 30]))

In [34]:
data[1]

(tensor([30, 25, 27]), tensor([25, 27, 29]))

In [35]:
bs = 1024
cut = int(len(data) * 0.8)
dls = DataLoaders.from_dsets(data[:cut], data[cut:], bs=bs, shuffle=False)

In [36]:
dls.one_batch()

(tensor([[40, 42, 29],
         [30, 25, 27],
         [29,  1,  1],
         ...,
         [ 2, 69, 65],
         [54, 62, 67],
         [58, 71,  8]]),
 tensor([[42, 29, 30],
         [25, 27, 29],
         [ 1,  1,  1],
         ...,
         [69, 65, 54],
         [62, 67, 58],
         [71,  8,  2]]))

In [37]:
def multi_output_ce(inp, targ):
    # inp = [sl, 1024, 85]
    # targ = [1024, sl]
    
    targ = targ.transpose(0,1).contiguous().view(-1) # [1024*sl]
    
    sl, bs, vocab_size = inp.shape
    inp = inp.view(-1,vocab_size) # [1024*sl, 85]
    
    return F.cross_entropy(inp, targ)


class CharXRNNModelMultiOutput(nn.Module):
    def __init__(self, vocab_size, n_hidden):
        super().__init__()
        self.vocab_size = vocab_size
        self.n_hidden = n_hidden
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.rnn = nn.RNN(256, 256) # [256, 256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, sl]
        
        bs = xs.shape[0] # 1024
        h = torch.zeros(1, bs, self.n_hidden) # [1,1024, 256]
        
        x = self.i_h(xs) # [1024, sl, 256]
        
        hs, h = self.rnn(x.transpose(0,1), h)
        # hs [sl, 1024, 256]
        # h [1, 1024, 256]
        
        out = self.h_o(hs) # [3, 1024, 85]
        
        return out
        

In [38]:
model = CharXRNNModelMultiOutput(vocab_size, 256)
learner = Learner(dls, model, loss_func=multi_output_ce)
learner.fit_one_cycle(10, 1e-2)

### So this does speed things up.. however we get pretty bad loss. Let's improve this by making things statefull

In [39]:
dls = DataLoaders.from_dsets(data[:cut], data[cut:], bs=bs, shuffle=False, drop_last=True)

class CharXRNNModelMultiOutputStateful(nn.Module):
    def __init__(self, vocab_size, n_hidden, bs):
        super().__init__()
        self.vocab_size = vocab_size
        self.n_hidden = n_hidden
        
        self.h = torch.zeros(1, bs, self.n_hidden) # [1,1024, 256]
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.rnn = nn.RNN(256, 256) # [256, 256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, sl]
        
        x = self.i_h(xs) # [1024, sl, 256]
        
        hs, h = self.rnn(x.transpose(0,1), self.h)
        # hs [sl, 1024, 256]
        # h [1, 1024, 256]
        
        self.h = h.detach()
        
        out = self.h_o(hs) # [3, 1024, 85]
        
        return out
        

In [40]:
model = CharXRNNModelMultiOutputStateful(vocab_size, 256, 1024)
learner = Learner(dls, model, loss_func=multi_output_ce)
learner.fit_one_cycle(10, 1e-2)

### Still not really a lot better, that's because the stuff doesn't align...

In [41]:
def group_chunks(ds, bs):
    m = len(ds) // bs
    new_ds = L()
    for i in range(m): new_ds += L(ds[i + m*j] for j in range(bs))
    return new_ds

In [42]:
cut = int(len(data) * 0.8)
dls = DataLoaders.from_dsets(
    group_chunks(data[:cut], bs), 
    group_chunks(data[cut:], bs), 
    bs=bs, drop_last=True, shuffle=False)

In [43]:
model = CharXRNNModelMultiOutputStateful(vocab_size, 256, 1024)
learner = Learner(dls, model, loss_func=multi_output_ce)
learner.fit_one_cycle(10, 1e-2)

### Now it's fast and has good performance!

### Let's simplify a couple of things by reordering and using batch_first=True on the RNN

In [44]:
def multi_output_ce(inp, targ):
    # inp = [1024, sl, 85]
    # targ = [1024, sl]
    
    targ = targ.view(-1) # [1024*sl]
    
    sl, bs, vocab_size = inp.shape
    inp = inp.view(-1,vocab_size) # [1024*sl, 85]
    
    return F.cross_entropy(inp, targ)


class CharXRNNModelMultiOutputStatefulBatchFirst(nn.Module):
    def __init__(self, vocab_size, n_hidden, bs):
        super().__init__()
        self.vocab_size = vocab_size
        self.n_hidden = n_hidden
        
        self.h = torch.zeros(1, bs, self.n_hidden) # [1,1024, 256]
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.rnn = nn.RNN(256, 256, batch_first=True) # [256, 256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, sl]
        
        x = self.i_h(xs) # [1024, sl, 256]
        
        hs, h = self.rnn(x, self.h)
        # hs [1024, sl, 256]
        # h [1, 1024, 256]
        
        self.h = h.detach()
        
        out = self.h_o(hs) # [1024, sl, 85]
        return out
        

In [45]:
model = CharXRNNModelMultiOutputStatefulBatchFirst(vocab_size, 256, 1024)
learner = Learner(dls, model, loss_func=multi_output_ce)
learner.fit_one_cycle(10, 1e-2)

### That means we can also use the CrossEntropyLossFlat loss 

In [ ]:
model = CharXRNNModelMultiOutputStatefulBatchFirst(vocab_size, 256, 1024)
learner = Learner(dls, model, loss_func=CrossEntropyLossFlat())
learner.fit_one_cycle(10, 1e-2)

In [58]:
class CharXMultiRNNModelMultiOutputStateful(nn.Module):
    def __init__(self, vocab_size, n_hidden, bs, n_layers):
        super().__init__()
        self.vocab_size = vocab_size
        self.n_hidden = n_hidden
        
        self.h = torch.zeros(n_layers, bs, self.n_hidden) # [2, 1024, 256]
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.rnn = nn.RNN(n_hidden, n_hidden, n_layers, batch_first=True) # [256, 256]
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, sl]
        
        x = self.i_h(xs) # [1024, sl, 256]
        
        hs, h = self.rnn(x, self.h)
        # hs [1024, sl, 256]
        # h [2, 1024, 256]
        
        self.h = h.detach()
        
        out = self.h_o(hs) # [1024, sl, 85]
        return out
        

In [59]:
model = CharXMultiRNNModelMultiOutputStateful(vocab_size, 256, 1024, 2)
learner = Learner(dls, model, loss_func=CrossEntropyLossFlat())
learner.fit_one_cycle(10, 1e-2)

### LSTMs

![lstm.png](lstm.png)

### Create custom LSTMCell according to the diagram above:

In [259]:
class LSTMCell(nn.Module):
    def __init__(self, ni, nh):
        super().__init__()
        self.ni = ni
        self.nh = nh
        
        self.forget_gate = nn.Linear(ni + nh, nh)
        self.input_gate = nn.Linear(ni + nh, nh)
        self.cell_gate = nn.Linear(ni + nh, nh)
        self.output_gate = nn.Linear(ni + nh, nh)
        
    def forward(self, inp, state):
        # inp [bs, ni]
        # state ([bs, nh], [bs, nh])
        h,c = state
        
        h = torch.cat([h, inp], dim=1) # [bs, ni+nh]
        
        forget = torch.sigmoid(self.forget_gate(h)) # [bs, nh]
        c = forget * c
        
        inp = torch.sigmoid(self.input_gate(h)) # [bs, nh]
        cell = torch.tanh(self.cell_gate(h)) # [bs, nh]
        
        inp = inp * cell 
        c = c + inp
        
        output = torch.sigmoid(self.output_gate(h))
        output = output * torch.tanh(c)
        
        return output, (output,c)

### And build the model:

In [264]:
class LSTMNet(nn.Module):
    def __init__(self, vocab_size, n_hidden, bs):
        super().__init__()
        
        self.state = [torch.zeros(bs, n_hidden), torch.zeros(bs, n_hidden)] # ([1024, 256], [1024, 256])
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.lstm = LSTMCell(n_hidden, n_hidden)
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, 3]
        
        x = self.i_h(xs) # [1024, 3, 256]
                
        outs = []
        out, self.state = self.lstm(x[:,0,:], self.state)
        outs.append(out)
        out, self.state = self.lstm(x[:,1,:], self.state)
        outs.append(out)
        out, self.state = self.lstm(x[:,2,:], self.state)
        outs.append(out)
        
        self.state = [i.detach() for i in self.state]
        
        out = self.h_o(torch.stack(outs, dim=1)) # [1024, sl, 85]
        return out
        

In [265]:
model = LSTMNet(vocab_size, 256, 1024)
learner = Learner(dls, model, loss_func=CrossEntropyLossFlat())

In [266]:
learner.fit_one_cycle(10, 5e-2)

### Factor out the LSTMLayer

In [263]:
class LSTMLayer(nn.Module):
    def __init__(self, cell, *cell_args):
        super().__init__()
        self.cell = cell(*cell_args)

    def forward(self, input, state):
        inputs = input.unbind(1)
        outputs = []
        for i in range(len(inputs)):
            out, state = self.cell(inputs[i], state)
            outputs += [out]
        return torch.stack(outputs, dim=1), state

In [267]:
class LSTMNet1(nn.Module):
    def __init__(self, vocab_size, n_hidden, bs, lstm_cell):
        super().__init__()
        
        self.h = [torch.zeros(bs, n_hidden), torch.zeros(bs, n_hidden)] # ([1024, 256], [1024, 256])
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.lstm = LSTMLayer(lstm_cell, n_hidden, n_hidden)
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, 3]
        
        x = self.i_h(xs) # [1024, 3, 256]
        
        outs, self.h = self.lstm(x, self.h)
        self.h = [i.detach() for i in self.h]
        
        out = self.h_o(outs) # [1024, sl, 85]
        return out
        

In [268]:
model = LSTMNet1(vocab_size, 256, 1024, LSTMCell)
learner = Learner(dls, model, loss_func=CrossEntropyLossFlat())
learner.fit_one_cycle(10, 5e-2)

### LSTMCell that "adds" instead of "concats" the input and hidden state together

In [269]:
class LSTMCellAdd(nn.Module):
    def __init__(self, ni, nh):
        super().__init__()
        self.ni = ni
        self.nh = nh
        
        self.forget_gate = nn.Linear(ni, nh)
        self.input_gate = nn.Linear(ni, nh)
        self.cell_gate = nn.Linear(ni, nh)
        self.output_gate = nn.Linear(ni, nh)
        
    def forward(self, inp, state):
        # inp [bs, ni]
        # state ([bs, nh], [bs, nh])
        h,c = state
        
        h = h + inp
        
        forget = torch.sigmoid(self.forget_gate(h)) # [bs, nh]
        c = forget * c
        
        inp = torch.sigmoid(self.input_gate(h)) # [bs, nh]
        cell = torch.tanh(self.cell_gate(h)) # [bs, nh]
        
        inp = inp * cell 
        c = c + inp
        
        output = torch.sigmoid(self.output_gate(h))
        output = output * torch.tanh(c)
        
        return output, (output,c)


In [270]:
model = LSTMNet1(vocab_size, 256, 1024, LSTMCellAdd)
learner = Learner(dls, model, loss_func=CrossEntropyLossFlat())
learner.fit_one_cycle(10, 5e-2)

### PyTorch is using a different LSTMCell:

![torch_lstm.png](torch_lstm.png)

In [171]:
class LSTMCellTorch(nn.Module):
    def __init__(self, ni, nh):
        super().__init__()
        self.ni = ni
        self.nh = nh
        
        self.forget_gate_inp = nn.Linear(ni, nh)
        self.forget_gate_h = nn.Linear(ni, nh)
        
        self.input_gate_inp = nn.Linear(ni, nh)
        self.input_gate_h = nn.Linear(ni, nh)
        
        self.cell_gate_inp = nn.Linear(ni, nh)
        self.cell_gate_h = nn.Linear(ni, nh)
        
        self.output_gate_inp = nn.Linear(ni, nh)
        self.output_gate_h = nn.Linear(ni, nh)
        
    def forward(self, inp, state):
        # inp [bs, ni]
        # state ([bs, nh], [bs, nh])
        h,c = state
        
        i = (self.input_gate_inp(inp) + self.input_gate_h(h)).sigmoid()
        f = (self.forget_gate_inp(inp) + self.forget_gate_h(h)).sigmoid()
        g = (self.cell_gate_inp(inp) + self.cell_gate_h(h)).tanh()
        o = (self.output_gate_inp(inp) + self.output_gate_h(h)).sigmoid()
        
        c = f * c + i * g
        output = o * c.tanh()
        
        return output, (output,c)

In [271]:
model = LSTMNet1(vocab_size, 256, 1024, LSTMCellTorch)
learner = Learner(dls, model, loss_func=multi_output_ce)
learner.fit_one_cycle(10, 5e-2)

### To use the nn.LSTMCell we have to change our LSTMLayer, since nn.LSTMCell has a slightly different API

In [274]:
class LSTMLayerTorch(nn.Module):
    def __init__(self, cell, *cell_args):
        super().__init__()
        self.cell = cell(*cell_args)

    def forward(self, input, state):
        inputs = input.unbind(1)
        outputs = []
        for i in range(len(inputs)):
            out, state = self.cell(inputs[i], state)
            state = (out, state)
            outputs += [out]
        return torch.stack(outputs, dim=1), state

class LSTMNetTorch(nn.Module):
    def __init__(self, vocab_size, n_hidden, bs):
        super().__init__()
        
        self.h = [torch.zeros(bs, n_hidden), torch.zeros(bs, n_hidden)] # ([1024, 256], [1024, 256])
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.lstm = LSTMLayerTorch(nn.LSTMCell, n_hidden, n_hidden)
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, 3]
        
        x = self.i_h(xs) # [1024, 3, 256]
        
        outs, self.h = self.lstm(x, self.h)
        self.h = [i.detach() for i in self.h]
        
        out = self.h_o(outs) # [1024, sl, 85]
        return out

In [275]:
model = LSTMNetTorch(vocab_size, 256, 1024)
learner = Learner(dls, model, loss_func=multi_output_ce)

In [276]:
learner.fit_one_cycle(10, 5e-2)

### Let's now use the native LSTM module

In [281]:
class LSTMNetTorch2(nn.Module):
    def __init__(self, vocab_size, n_hidden, bs, n_layers):
        super().__init__()
        
        self.h = [torch.zeros(n_layers, bs, n_hidden), torch.zeros(n_layers, bs, n_hidden)] # ([1024, 256], [1024, 256])
        
        self.i_h = nn.Embedding(vocab_size, n_hidden) # [85, 256]
        self.lstm = nn.LSTM(n_hidden, n_hidden, n_layers, batch_first=True)
        
        self.h_o = nn.Linear(n_hidden, vocab_size) # [256, 85]
        
    def forward(self, xs):
        # xs = [1024, 3]
        
        x = self.i_h(xs) # [1024, 3, 256]
        
        outs, self.h = self.lstm(x, self.h)
        self.h = [i.detach() for i in self.h]
        
        out = self.h_o(outs) # [1024, 3, 85]
        return out

In [282]:
model = LSTMNetTorch2(vocab_size, 256, 1024, 1)
learner = Learner(dls, model, loss_func=multi_output_ce)
learner.fit_one_cycle(10, 5e-2)

### After this, we could continue with more NLP based stuff and get into transformers etc, we would do that by following this [course](https://www.youtube.com/playlist?list=PLtmWHNX-gukKocXQOkQjuVxglSDYWsSh9)

Two great resources:

- https://colah.github.io/posts/2015-08-Understanding-LSTMs/
- http://karpathy.github.io/2015/05/21/rnn-effectiveness/